---
title: "Defining Microenvironments and Risks"
author: "Ruth C E Bowyer"
date: "`r format(Sys.Date())`"
output:
  github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## **0. About**

Some early thoughts on some essential definitions for DyME-chh 


## **1. Exposure variable**

For investigative purposes - be key to look at **wet bulb temperature (Tw)** (which is also a consideration of relative humidty x heat, where relative humidity is %) 

Need to look out relative humidity vars in the CPM as HADs

Tw of 35oC (but more recent research of 31.5 oC suggested) as the temperature an individual can survive at for 6 hours or less. (air temperature of around 40 oC)


## **2. Microenvironments to consider**

Link to housing, but start with defining a change in heat exposure related to outdoor head and time of day - need to review literature to define under what conditions indoor no cooling is likely to be hotter

- Indoors, work - assume % as air conditioned
- Indoors, home - very low % cooled - fan cooling can be detremental if the humidity is high
- In vechile transit
- Outdoors 

**Then expand to include:**

- Type of housing 
- Shaded vs non-shaded outdoor


## **3. High risk groups**

(Much of this framework from the PHG summary)

**At risk because of compromised thermoregulation:**

- Younger children
- Older adults
- Dehydrated (alcohol consumption)
- People with chronic conditions/MLTC
- People using certain medications 
- Pregant people & their foetuses 

**At risk because of high heat exposure:**

 - Occupational (outdoor workers, factory workers, military)
 - Athletes
 - Pedestrians
 - Lower SES individuals
 - Individuals with poor housing stock 